enum Slice {
    ALERTAS = 'ALERTAS',
    ALERTAS_SECUNDARIOS = 'ALERTAS_SECUNDARIOS',
    HELPER = 'HELPER',
    USER_SLICE = 'USER',
    LIST_ACTIVES_TUTORS = 'LIST_ACTIVES_TUTORS',
    LIST_ACTIVES_PETS = 'LIST_ACTIVES_PETS',
    ARCHIVE_TUTOR = 'ARCHIVE_TUTOR',
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAIL = "LOGIN_FAIL",
    LOGOUT = "LOGOUT"
  }
  
  export default Slice;